---
title: "hmda balanced"
author: "Justina Zou"
date: "July 9, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(readr)

set.seed(2019)

# data <- read_csv("./data/hmda_nc_encode.csv")
data <- read_csv("./data/hmda_nc_noencode.csv") # note, if working with the not encoded dataset, need to filter
new_d <- data
```

# Balance dataset

Creates balanced datasets.

```{r}
num_samps <- 50000

# Function that returns a dataset with half of the points from
# true_col with a value equal to true
# and half of the points from
# false_col with a value equal to false
# If true and/or false are strings, encase them with single quotes
half <- function(data, true_col, false_col, true, false) {
  true_data <- data %>% filter_(paste0(true_col, "==", true))
  false_data <- data %>% filter_(paste0(false_col, "==", false))
  half_d <- sample_n(true_data, num_samps)
  half_d <- rbind(half_d, sample_n(false_data, num_samps))
  return(half_d)
}

# Dataset with 50/50 approve/deny
half_ad <- half(new_d, "loan_status", "loan_status", 
                true=1, false=0)

# Dataset with 50/50 black/white
half_wb <- half(new_d, true_col="applicant_race_name_1",
                false_col="applicant_race_name_1",
                true="'Black or African American'", false="'White'")

# 50/50 hispanic/not hispanic
half_hn <- half(new_d, true_col="applicant_ethnicity_name",
                false_col="applicant_ethnicity_name",
                true="'Hispanic or Latino'", false="'Not Hispanic or Latino'")

# 50/50 female/male
half_fm <- half(new_d, true_col="applicant_sex_name",
                false_col="applicant_sex_name",
                true="'Female'", false="'Male'")

# # Dataset with 50/50 black/white
# half_wb <- half(new_d, true_col="applicant_race_name_1_Black_or_African_American",
#                 false_col="applicant_race_name_1_White",
#                 true=1, false=1)
# 
# # 50/50 hispanic/not hispanic
# half_hn <- half(new_d, true_col="applicant_ethnicity_name_Hispanic_or_Latino",
#                 false_col="applicant_ethnicity_name_Not_Hispanic_or_Latino",
#                 true=1, false=1)
# 
# # 50/50 female/male
# half_fm <- half(new_d, true_col="applicant_sex_name_Female",
#                 false_col="applicant_sex_name_Male",
#                 true=1, false=1)
```










